File Name,Domain Name, Private_IP_Found_In_Default_DNS,Private_IP_Found_In_Public_DNS,Default DNS IP's found in Public DNS, Domain Doesn't Work but IP Does,Response Code,Default DNS IP Address,Public DNS Response Codes,All Domain Response Codes,All Default DNS Response Codes,All Public DNS Response Codes,,Method
ISP_../results/BS_IINet_25APr_2024.csv,https://www.stockspot.com.au/,FALSE,FALSE,TRUE,FALSE,200,"['\'HTTPSConnectionPool(host=\\\'13.210.224.193\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.210.224.193\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'13.55.150.53\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.55.150.53\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'3.25.13.159\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'3.25.13.159\\\'. (_ssl.c:1000)"")))\'']","['\'HTTPSConnectionPool(host=\\\'13.55.150.53\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.55.150.53\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'3.25.13.159\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'3.25.13.159\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'13.210.224.193\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.210.224.193\\\'. (_ssl.c:1000)"")))\'']",['200'],"['\'HTTPSConnectionPool(host=\\\'13.210.224.193\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.210.224.193\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'13.55.150.53\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.55.150.53\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'3.25.13.159\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'3.25.13.159\\\'. (_ssl.c:1000)"")))\'']","['\'HTTPSConnectionPool(host=\\\'13.55.150.53\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.55.150.53\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'3.25.13.159\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'3.25.13.159\\\'. (_ssl.c:1000)"")))\'', '\'HTTPSConnectionPool(host=\\\'13.210.224.193\\\'; port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1; ""[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch; certificate is not valid for \\\'13.210.224.193\\\'. (_ssl.c:1000)"")))\'']","['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",Unblocked
ISP_../results/BS_IINet_25APr_2024.csv,http://www.anime-sharing.com/,FALSE,FALSE,FALSE,FALSE,200,['200'],['403'],['200'],['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://www.imovies.cc,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='www.imovies.cc'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a3ca10>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='www.imovies.cc'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a3ca10>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,http://animereborn.io/,FALSE,FALSE,FALSE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,http://unblockproject.pw/,FALSE,FALSE,FALSE,FALSE,200,['200'],"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']",['200'],['200'],"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://animelon.com/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='animelon.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074974d0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='animelon.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074974d0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://getpopcorntime.is/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='getpopcorntime.is'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a3e7b0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['442'],"[""HTTPSConnectionPool(host='getpopcorntime.is'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a3e7b0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['442'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://animehd47.com/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='animehd47.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a6ddf0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['404'],"[""HTTPSConnectionPool(host='animehd47.com'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a6ddf0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['404'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://lookmovie.ag/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='lookmovie.ag'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107467890>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['200'],"[""HTTPSConnectionPool(host='lookmovie.ag'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107467890>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://katcr.to/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='katcr.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111aab740>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='katcr.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111aab740>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,http://nocensor.surf/,FALSE,FALSE,FALSE,FALSE,200,['200'],[''],['200'],['200'],[''],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://nocensor.casa/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='nocensor.casa'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1071ff920>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['200'],"[""HTTPSConnectionPool(host='nocensor.casa'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1071ff920>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,http://nocensor.fun/,FALSE,FALSE,FALSE,FALSE,200,['200'],['412'],['200'],['200'],['412'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://unblockproject.icu/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='unblockproject.icu'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1072688c0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['400'],"[""HTTPSConnectionPool(host='unblockproject.icu'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1072688c0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['400'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://unblockproject.info/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='unblockproject.info'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1072d5fd0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['410'],"[""HTTPSConnectionPool(host='unblockproject.info'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1072d5fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['410'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,http://123unblock.space/,FALSE,FALSE,FALSE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://123unblock.fun/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='123unblock.fun'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111d08a40>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['200'],"[""HTTPSConnectionPool(host='123unblock.fun'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111d08a40>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,http://unbl0ck.online/,FALSE,FALSE,FALSE,FALSE,200,['200'],"['429', '200']",['200'],['200'],"['429', '200']","['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,http://123unblock.icu/,FALSE,FALSE,FALSE,FALSE,200,['200'],[''],['200'],['200'],[''],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,http://prox4you.club/,FALSE,FALSE,FALSE,FALSE,200,['200'],['200'],['200'],['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://prox4you.pro/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='prox4you.pro'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9d370>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['410'],"[""HTTPSConnectionPool(host='prox4you.pro'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9d370>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['410'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,http://prox4you.info/,FALSE,FALSE,FALSE,FALSE,200,['200'],['410'],['200'],['200'],['410'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",DNS Poisoning
ISP_../results/BS_IINet_25APr_2024.csv,https://unblocked.to/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='unblocked.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a6d430>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","[""HTTPSConnectionPool(host='unblocked.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a6d430>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],"['""(\'Connection aborted.\'; RemoteDisconnected(\'Remote end closed connection without response\'))""']","['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://prostylex.org/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='prostylex.org'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9fe90>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['200'],"[""HTTPSConnectionPool(host='prostylex.org'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9fe90>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://torrents.io,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='torrents.io'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111b30680>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],[''],"[""HTTPSConnectionPool(host='torrents.io'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111b30680>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],[''],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://katcr.co/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='katcr.co'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074665a0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],[''],"[""HTTPSConnectionPool(host='katcr.co'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074665a0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],[''],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://kikass.to/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='kikass.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111d4ab70>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='kikass.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111d4ab70>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://kat.sx/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='kat.sx'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9f380>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='kat.sx'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9f380>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://kickass.sx/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='kickass.sx'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9caa0>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['403'],"[""HTTPSConnectionPool(host='kickass.sx'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111a9caa0>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['403'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking
ISP_../results/BS_IINet_25APr_2024.csv,https://kickass1.to/,FALSE,FALSE,FALSE,TRUE,HTTPSConnectionPool(host='kickass1.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111b29c10>: Failed to establish a new connection: [Errno 61] Connection refused')),['200'],['200'],"[""HTTPSConnectionPool(host='kickass1.to'; port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x111b29c10>: Failed to establish a new connection: [Errno 61] Connection refused'))""]",['200'],['200'],"['False', 'False', 'N/A', 'False', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'False', 'N/A', 'False', 'N/A', 'N/A', 'False', 'N/A', 'False', 'False', 'False', 'N/A', 'False', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']",URL Blocking